### ISSUE TITLE
PHP code migration guide

### ISSUE THREAD

**Issue by leonardomarino** [duosecurity/duo_universal_php#3]
Hi,

Would it be possible to generate a WebSDK v2 to WebSDK v4 Code Migration Guide using PHP in an analogous way to what is shown here: https://github.com/duosecurity/duo_python/pull/57/files

I am trying to migrate an application https://github.com/leonardomarino/duo_auth/blob/master/duo_auth.php to the new SDK and your help would be greatly appreciated.

Thanks, Leonardo

**Comment by AaronAtDuo** [comment]
@leonardomarino Unfortunately, this is unlikely to be something we have the capacity to provide any time soon.

Is there any specific part of the migration that is giving you trouble, which we may be able to provide some tips on?

**Comment by leonardomarino** [comment]
Hi @AaronAtDuo thanks for your message. Would it be possible to post another implementation example without the use of Slim and slim-session? I think that would clarify things a bit. Thanks again for your attention.

**Comment by AaronAtDuo** [comment]
@leonardomarino The 'session' pieces of the example are definitely going to be heavily dependent on the PHP framework in use.  It looks like you're using roundcubemail, If I'm reading your repo code correctly?  It looks like rcmail has a session storage mechanism, described at http://roundcubemail.sourceforge.net/doc/phpdoc-0.9.0/Framework/Core/rcube_session.html.  That might be your best bet?

We're not going to be able to provide additional framework examples at this time unfortunately.  Hopefully the information above is useful.

**Comment by leonardomarino** [comment]
Thanks @AaronAtDuo that is very helpful. I am going to close the ticket.
