### ISSUE TITLE
Make license more clear

### ISSUE THREAD

**Issue by gruberroland** [duosecurity/duo_universal_php#8]
There is a little difference in point "3." between the LICENSE file and https://opensource.org/license/bsd-3-clause/ (which is referenced in the code). It would be great if you can update the LICENSE file and also add the license to composer.json.

Thanks in advance for your help.

**Comment by AaronAtDuo** [comment]
@gruberroland How does https://github.com/duosecurity/duo_universal_php/pull/9 look?  Is that what you had in mind?

**Comment by gruberroland** [comment]
This looks perfect. :)
